name: PR Build & Release

on:
  push:
    branches:
      - releases   # Trigger für finalen Release nach Merge

jobs:
  # -------------------
  # PR Build (nur Tests + Artifacts)
  # -------------------
  build_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # alle Tags verfügbar

      - name: Build
        run: sh build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multiarch-binaries
          path: build/*
          retention-days: 31

  # -------------------
  # Release nach Merge
  # -------------------
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # alle Tags verfügbar

      - name: Download Artifacts from PR
        uses: actions/download-artifact@v4
        with:
          name: multiarch-binaries
          path: Binaries/

      - name: Find Version Tag
        id: get_tag
        run: echo "tag=$(git describe --tags --match 'v*' --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: Release ${{ steps.get_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
