name: Lint

on:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              run: |
                curl -fsSL https://pyenv.run | bash
                echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
                echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
                echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
                $HOME/.pyenv/bin/pyenv install 3.12
                $HOME/.pyenv/bin/pyenv global 3.12
                pip install cpplint

            - name: Run cpplint
              run: |
                cpplint --recursive ./src ./include